
spring.datasource:
  druid:
    url:  jdbc:mysql://localhost:3306/blade
    username: root
    password: root
    db-type: com.alibaba.druid.pool.DruidDataSource
    initial-size: 5
    min-idle: 5
    max-active: 20


###mybatis 配置####
mybatis:
  type-aliases-package: com.hiynn.entity
  mapper-locations: classpath:mybatis/*.xml
  configuration:
    call-setters-on-nulls: true


