
server:
  port: 18002
spring:
  application:
    name: ky-data
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379


logging:
  config: 'classpath:logback-spring.xml'
  path: 'log'
  level:
    root: debug

