server:
  port: 14433

spring:
  datasource:
    url: jdbc:mysql://mysql:3306/training?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true
    username: root
    password: 123456
    type: com.mysql.cj.jdbc.MysqlDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: TrainningHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: file:${file-root-path}


mybatis:
  type-aliases-package: com.guiji.training.entity
  mapper-locations: classpath*:/mappers/*xml

file-root-path: /home/yykl/apps/file_test
zip-root-path: /home/yykl/apps/clone/datasets
speex-to-wav: /home/yykl/apps/tool/spx2wav

ogging:
  level:
    org:
      springframework:
        web: info
    com:
      guiji:
        training:
          dao: debug
clone:
  train:
    ip: 47.98.223.225
    username: clone
    password: clone123clone
    port: 20273