
spring:
  datasource:
    url: jdbc:mysql://192.168.100.28:3306/test
    username: root
    password: chenkuo123456
#    driverClassName: com.mysql.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 28770000
      minimum-idle: 2
  data:
    mongodb:
      port: 27017
      database: enterpriseLib
      host: 192.168.100.57
      tyc:
        collection:
          # 基本信息
          basic-info: "tyc-basicInfo"
          # 动产抵押
          dcdy: "tyc-dcdy"
          # 企业行政处罚信息核验
          xzcf: "tyc-xzcf"
          # 企业经营异常核验
          jyyc: "tyc-jyyc"
          # 企业经营异常核验
          ktgg: "tyc-ktgg"
          # 被执行人核验
          bzxr: "tyc-bzxr"
          # 被执行人核验
          fygg: "tyc-fygg"
          # 法院判决信息核验
          fypj: "tyc-fypj"
          # 失信人信息核验
          sxr: "tyc-sxr"
          # 实名认证(尊享版)
          smrz: "tyc-smrz"
          # 身份证OCR识别（尊享版）
          sfzsb: "tyc-sfzsb"
          # 银行卡OCR识别（尊享版）
          yhksb: "tyc-yhksb"
          # 股权出质
          gqcz: "tyc-gqcz"
      sjb:
        collection:
          # 基本信息
          basic-info: "sjb-basicInfo"
          # 动产抵押
          dcdy: "sjb-dcdy"
          # 企业行政处罚信息核验
          xzcf: "sjb-xzcf"
          # 企业经营异常核验
          jyyc: "sjb-jyyc"
          # 企业经营异常核验
          ktgg: "sjb-ktgg"
          # 被执行人核验
          bzxr: "sjb-bzxr"
          # 被执行人核验
          fygg: "sjb-fygg"
          # 法院判决信息核验
          fypj: "sjb-fypj"
          # 失信人信息核验
          sxr: "sjb-sxr"
          # 实名认证(尊享版)
          smrz: "sjb-smrz"
          # 身份证OCR识别（尊享版）
          sfzsb: "sjb-sfzsb"
          # 银行卡OCR识别（尊享版）
          yhksb: "sjb-yhksb"
          # 股权出质
          gqcz: "sjb-gqcz"

#      username: root
#      password: 123456

  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: validate
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  application:
    name: enterprise-lib
  http:
    encoding:
      enabled: true
      charset: utf-8
      force: true
logging:
  config: classpath:logback-spring.xml
  path: logs

# 全局日志等级
log-level: debug
server:
  port: 8888














